### ISSUE TITLE
The need for `precision` as an attribute in `ecx`, `nsec`, etc outputs

### ISSUE THREAD

**Issue by dbarneche** [open-AIMS/bayesnec#128]
Is the output attribute `precision` in ecx, nsec, etc really necessary?

Now in cases where `newdata` is provided to these functions (or `average_*`, `compare_*`), or the raw data is used for predictions (via `make_newdata = FALSE`, there is no precision, so that needs to be different.
In those cases I have set them specifically to strings, see e.g. [here](https://github.com/open-AIMS/bayesnec/blob/125d04adfa437d9a919130c1e029116ca5fccf8e/R/helpers.R#L618).

If `make_newdata = TRUE` (maintained as default for compatibility with previous version) then output attribute `precision` is still the argument precision (i.e. a number).

Do you agree with that approach?

**Comment by beckyfisher** [comment]
Calls to ecx and nsec do not require the same level of flexibility in the context of allowing newdata to be supplied manually, as this is and should be handled within the function itself. The argument precision controls how precisely the nsec or ecx value is estimated, with x-range allowing estimation beyond the existing range of the observed data (otherwise the default range) which can be useful in a small number of cases.
 There is also no reasonable case where estimating these from the raw data would be of value, because both functions would simply return one of the treatment concentrations, making NOEC a better metric in that case.
