### ISSUE TITLE
Error in while (!are_good & n <= n_trials) { :  missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by beckyfisher** [open-AIMS/bayesnec#42]
The model nechorme4pwr is returning an error in the binomial case where there is only 1 trial:
#Error in while (!are_good & n <= n_trials) { : 
#missing value where TRUE/FALSE needed
Note this doesn't seem to be throwing an error for the other models.
reproducible example below:
#try with inbuilt data
library(bayesnec)
library(tidyverse)
data(nec_data)
nec_data <- nec_data %>% 
  mutate(tot=1,
         suc=as.integer(round(y*tot)))

test <- bnec(data = nec_data, 
                           x_var = "x", 
                           y_var = "suc", 
                           trials_var = "tot",
                           model = "nechorme4pwr")

**Comment by dbarneche** [comment]
Hey @beckyfisher 

This is because on lines [22--24](https://github.com/open-AIMS/bayesnec/blob/6529a6128024b5fdd280de93c78939e3a27e97c9/R/define_prior.R#L22) of the function `define_prior` we have the following evaluations:

```
response <- family$linkfun(response)
response <- response[is.finite(response)]
```

The example you gave only has 0 or 1s as part of the response vector, which means -Inf and Inf on the link function (logit in this case). That causes the response vector to be empty, with consequential errors in the priors specification. The error line you reported is spat out from `make_inits` because that's when the prior strings generated by `define_prior` are actually evaluated to generate initial values. However, because they contain NAs, `make_inits` fails. This is the prior structure generated in your example:

```
Browse[1]> priors
                      prior class coef group resp dpar nlpar                                           bound source
               normal(0, 1)     b                       beta                                                   user
             normal(NA, NA)     b                        top                                                   user
 gamma(5, 2.28313180499098)     b                        nec <lower=0.03234801324009,upper=3.22051966293556>   user
               normal(0, 1)     b                      slope                                                   user
             normal(NA, NA)     b                        bot                                                   user
```

So I've added an error statement in my commit above to break the code in the correct function. But I'm not quite sure how to fix this issue here. Should we just add some tiny decimals do the response to keep it within the 0-1 range when it's binomial? If so just let me know and I can implement the tweak and close the issue.

**Comment by beckyfisher** [comment]
Hi Diego - that sounds ok to me, but doesn;t it need to take an integer?

**Comment by dbarneche** [comment]
Yes, but for the actual model run. The proposed modification would only take place inside `define_prior` to create the correct prior structure. It does not modify / return the response vector.
